name: Run Tests and Lint

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Display User Info
        env:
          FULL_NAME: ${{ secrets.FULL_NAME }}
          GROUP_NUMBER: ${{ secrets.GROUP_NUMBER }}
        run: echo "Full Name: $FULL_NAME, Group: $GROUP_NUMBER, GitHub Username: ${{ github.actor }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s tests

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
